import 'package:flutter/foundation.dart';

/// Deployment target for a build.
enum DeploymentTarget { local, staging, production }

/// Runtime configuration for an ArogyaMitra app.
///
/// Values arrive through `--dart-define` so that no key is committed to source
/// control (PRD 16: secrets stay out of the repository). The defaults point at
/// the local Supabase stack, which ships with well-known development keys.
@immutable
class AppEnvironment {
  const AppEnvironment({
    required this.supabaseUrl,
    required this.supabasePublishableKey,
    required this.target,
    this.directionsUrlTemplate = _defaultDirectionsTemplate,
  });

  /// Reads configuration from the compile-time environment.
  ///
  /// Example:
  /// ```
  /// flutter run -d chrome \
  ///   --dart-define=SUPABASE_URL=https://<project>.supabase.co \
  ///   --dart-define=SUPABASE_PUBLISHABLE_KEY=<key> \
  ///   --dart-define=DEPLOYMENT_TARGET=staging
  /// ```
  factory AppEnvironment.fromDartDefines() {
    const target = String.fromEnvironment(
      'DEPLOYMENT_TARGET',
      defaultValue: 'local',
    );

    final resolvedTarget = DeploymentTarget.values.firstWhere(
      (t) => t.name == target,
      orElse: () => DeploymentTarget.local,
    );

    // Android emulators need 10.0.2.2 to access host machine's localhost
    final isAndroid = !kIsWeb && defaultTargetPlatform == TargetPlatform.android;
    final defaultUrl = isAndroid ? _androidLocalUrl : _localSupabaseUrl;

    const url = String.fromEnvironment(
      'SUPABASE_URL',
      defaultValue: '',
    );
    const key = String.fromEnvironment(
      'SUPABASE_PUBLISHABLE_KEY',
      defaultValue: _localPublishableKey,
    );

    final actualUrl = url.isEmpty ? defaultUrl : url;

    if (resolvedTarget != DeploymentTarget.local &&
        (actualUrl == _localSupabaseUrl || actualUrl == _androidLocalUrl || key == _localPublishableKey)) {
      throw StateError(
        'A $target build must supply SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY '
        'via --dart-define. Refusing to start with local development keys.',
      );
    }

    return AppEnvironment(
      supabaseUrl: actualUrl,
      supabasePublishableKey: key,
      target: resolvedTarget,
      directionsUrlTemplate: const String.fromEnvironment(
        'DIRECTIONS_URL_TEMPLATE',
        defaultValue: _defaultDirectionsTemplate,
      ),
    );
  }

  /// Supabase project URL.
  final String supabaseUrl;

  /// Publishable (anon) key. Safe for clients: every table is behind RLS.
  final String supabasePublishableKey;

  final DeploymentTarget target;

  /// Directions handoff template with `{lat}` and `{lon}` placeholders. Kept
  /// configurable because the approved mapping provider is deployment specific
  /// (PRD 9, PRD 29).
  final String directionsUrlTemplate;

  bool get isLocal => target == DeploymentTarget.local;
  bool get isProduction => target == DeploymentTarget.production;

  /// True while external integrations run against mock adapters (PRD 14.4, 23).
  bool get usesMockAdapters => target != DeploymentTarget.production;

  static const _localSupabaseUrl = 'http://127.0.0.1:54321';
  static const _androidLocalUrl = 'http://10.0.2.2:54321';

  /// Local-only publishable key generated by `supabase start`. This is a
  /// documented development default, not a secret.
  static const _localPublishableKey =
      'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH';

  static const _defaultDirectionsTemplate =
      'https://www.google.com/maps/dir/?api=1&destination={lat},{lon}';
}
